### ISSUE TITLE
fix: Enhance Verse Match Title with Animated Gradient Text

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#58]
### Overview

We aim to improve the user experience of our Versify application by implementing an animated gradient text effect for the main title in `Bible-verse-similarity`. We'll be using the Animated Gradient Text component from Magic UI as a reference for this implementation.

### Tasks

  - [ ] Review the documentation at https://magicui.design/docs/components/animated-gradient-text
  - [ ] Create a new component for the animated gradient text
  - [ ] Replace the current title implementation with the new animated gradient text component

**Comment by arelymartinez16** [comment]
I would like to work on this!

**Comment by JustinhSE** [comment]
Thanks for your interest, just assigned you!
