### ISSUE TITLE
feat: Verse of the Day w/ YouVersion API and Tweet Card Display

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#61]
## Overview
Add a "Verse of the Day" feature using the YouVersion API to fetch daily verses and display them using the MagicUI Tweet Card component. This feature will provide users with daily inspiration in a visually appealing format.

## Tasks

1. Install and set up YouVersion API
   - [ ] Review documentation within this [api](https://github.com/Glowstudent777/YouVersion-API-NPM)
   - [ ] Run `npm install @glowstudent/youversion`
   - [ ] Import the YouVersion module in the project
   - [ ] Create a function to fetch the Verse of the Day using YouVersion API

2. Create a Verse of the Day component
   - [ ] Use the [Tweet Card component](https://magicui.design/docs/components/tweet-card) as a base
   - [ ] Customize the component to display the Verse of the Day content (exclude version)
   - [ ] Set the title of the Tweet Card to "Verse of the Day"

5. Integrate Verse fetching with the display component
   - [ ] Fetch the Verse of the Day when the component mounts
   - [ ] Update the Tweet Card component with the fetched verse data
   - [ ] Display a fallback message if the verse fetching fails

6. Implement caching to reduce calls (optional)
   - [ ] Store the fetched verse locally to reduce API calls
   - [ ] Update the cached verse at midnight in the user's local time zone

**Comment by ciaracade** [comment]
I'd like to take this!

**Comment by JustinhSE** [comment]
Yea for sure!

**Comment by ciaracade** [comment]
Thank you! ^^

**Comment by JustinhSE** [comment]
Any update regarding this @ciaracade? Let me know if you need help

**Comment by JustinhSE** [comment]
Hey @ciaracade, just checking in for the status on this issue?

**Comment by ciaracade** [comment]
Hi, working on this over winter break ;)

**Comment by JustinhSE** [comment]
Alright great, thanks for the status update!

**Comment by JustinhSE** [comment]
Hey @ciaracade it has been a few months. Our repo is getting updated so wondering if you still would want this issue?

**Comment by ciaracade** [comment]
Yes, still want it. Waiting until school to finish haha
