### ISSUE TITLE
feat: Ctrl/Cmd + Enter Listener 

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#72]
## Overview

We need to add a keyboard shortcut (Ctrl+Enter) for the "Find Similar Version" button on the Verse Match page. This enhancement will allow users to trigger the button's functionality without using the mouse, improving accessibility and user efficiency.

## Tasks

- [ ] Implement event listener for Ctrl+Enter combination
  - Add a keydown event listener
  - Check for Ctrl+Enter key combination

- [ ] Link shortcut to button functionality
  - Identify the function called when the "Find Similar Version" button is clicked
  - Trigger this function when Ctrl+Enter is pressed and input is present

- [ ] Update UI to indicate shortcut availability
  - Add a tooltip or visual indicator to the button showing the Ctrl+Enter shortcut

**Comment by Awnder** [comment]
Would like to take this on! No timeline but will figure it out if you want one

**Comment by Awnder** [comment]
I don't see "Find Similar Version". Do you mean "[Find Similar Verses](https://github.com/Namit2111/bible-verse-finder/blob/6588c81d49f23d8cfbd711f2f3337a4f65d1c81d/frontend/app/versematch/page.tsx#L126)"?

**Comment by JustinhSE** [comment]
Yes sorry, typo
