### ISSUE TITLE
feat: Language detection for non-English input

### ISSUE THREAD

**Issue by JustinhSE** [Namit2111/bible-verse-finder#74]
### Overview

Implement language detection and translation for non-English input in the VerseMatch feature using Google Translate. When users type verses in languages other than English and click `Find Similar Verses`, the system should use Google Translate to detect the language, translate the input to English, and then proceed with the verse vectorization and matching process.

### Tasks

- [ ] Set up Google Cloud project and enable the Cloud Translation API.
- [ ] Install the Google Cloud Translation library:
  ```bash
  npm install @google-cloud/translate
- [ ] Modify the existing "Find Similar Verses" function to incorporate Google Translate
- [ ] Implement error handling for cases where translation fails


This issue is still in early development, so feel free to thread any ideas, suggestions or feedback!

**Comment by JustinhSE** [comment]
Considerations: 

- Only do this for languages other than English. English input should not call this
- Output should be converted to that language including our "void" output message

**Comment by Agastya18** [comment]
let me try @JustinhSE

**Comment by JustinhSE** [comment]
@Agastya18 do you mind giving me a high level overview of how you are thinking of proceeding with this?

**Comment by RamonSaturninoM** [comment]
Has this been solved?, I can try to set an overview and then try to implement it :)

**Comment by JustinhSE** [comment]
Go ahead!
